# Generated by Django 4.0.4 on 2022-04-15 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_favoriteitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='added_by',
        ),
    ]
